install:
- make insights

script:
- make build
- docker images
- |
  if [[ "${TRAVIS_BRANCH}" = "master" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker tag cppinsights-webfrontend $DOCKER_USERNAME/cppinsights-webfrontend
    docker push $DOCKER_USERNAME/cppinsights-webfrontend
  fi
